#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
One-click Classification Pipeline: Morgan(1024) -> pipeline.py Training -> Auto-select Best Fold (best_model) -> Optional Prediction

Modifications:
- Morgan feature file `swelling_ratio_morgan.csv` is saved in:
  LIGHT_platform-main/Supervised_Learning/Classification_Model/results/<task_name>/features/
- The file generated by pipeline.py (e.g., `swelling_ratio_morgan_CLS9.csv`) will also be saved in the same `features` directory.
- Added file existence checks to skip completed steps.
"""

import argparse
import subprocess
from pathlib import Path
import shutil
import pandas as pd
import os
import sys

# ============= Utility Functions =============
def run_cmd(cmd: list):
    if cmd and cmd[0] == "python":
        cmd[0] = sys.executable

    print("\n====== RUN CMD ======")
    print(" ".join(cmd))
    print("=====================\n")
    subprocess.run(cmd, check=True)


# ============= STEP 1: Morgan Fingerprints (1024 bits) =============
def run_morgan(raw_csv: str, morgan_csv: str, polymer_cols, other_cols):
    cmd = [
        "python", "morgan_pooling.py",
        "--in_csv", raw_csv,
        "--out_csv", morgan_csv,
        "--alpha", "3",
        "--radius", "3",
        "--nbits", "1024",
        "--polymer_cols", *polymer_cols,
    ]
    if other_cols:
        cmd += ["--other_cols", *other_cols]

    run_cmd(cmd)


# ============= STEP 2: Classification Training via pipeline.py =============
def run_pipeline(morgan_csv, src_col, threshold, class_col, task_dir):
    """
    Equivalent to:
    python pipeline.py \
        --in_csv smm_morgan.csv \
        --src_col "Swelling Ratio (times)" \
        --threshold 9 \
        --use_cv10 1 \
        --save_fold_models 1 \
        --base_save_root results/SwellingRatio
    """
    cmd = [
        "python", "pipeline.py",
        "--in_csv", morgan_csv,
        "--src_col", src_col,
        "--threshold", str(threshold),
        "--class_col", class_col,
        "--use_cv10", "1",
        "--save_fold_models", "1",
        "--base_save_root", str(task_dir),
    ]
    run_cmd(cmd)


# ============= STEP 3: Auto-select Best Fold (Maximize Acc_class_1) =============
def select_best_model(task_dir: Path, threshold: float):
    """
    Automatically search for `rf_cls_cv10*` directories under `results/<task_name>/`
    and select the best model based on the maximum Acc_class_1.
    """
    
    # Construct expected model directory name
    threshold_int = int(threshold)
    expected_dir_name = f"rf_cls_cv10_t{threshold_int}"
    expected_dir = task_dir / expected_dir_name
    
    # If directory does not exist, try to find any directory starting with rf_cls_cv10
    if not expected_dir.exists():
        dirs = [d for d in task_dir.iterdir() if d.is_dir() and d.name.startswith("rf_cls_cv10")]
        if not dirs:
            raise RuntimeError(f"No rf_cls_cv10* directory found in: {task_dir}")
        rf_dir = dirs[0]
    else:
        rf_dir = expected_dir
    
    print(f"[INFO] Identified training directory: {rf_dir}")
    
    # Check if best_model already exists
    best_model_path = rf_dir / "cv10" / "best_model.joblib"
    if best_model_path.exists():
        print(f"[INFO] Best model already exists, skipping selection step: {best_model_path}")
        return best_model_path, rf_dir / "cv10", rf_dir
    
    # Load metrics table
    metrics_file = rf_dir / "cv10_metrics.csv"
    if not metrics_file.exists():
        raise FileNotFoundError(f"Model metrics file not found: {metrics_file}")

    df = pd.read_csv(metrics_file)

    if "Acc_class_1" not in df.columns:
        raise ValueError("Missing 'Acc_class_1' column in cv10_metrics.csv")

    # Select the fold with the highest Acc_class_1
    best_row = df.sort_values("Acc_class_1", ascending=False).iloc[0]
    best_fold = int(best_row["fold"])

    print(f" Best Fold: fold_{best_fold:02d}, Acc_class_1={best_row['Acc_class_1']:.4f}")

    # Locate the corresponding model file
    cv10_dir = rf_dir / "cv10"
    src = cv10_dir / f"fold_{best_fold:02d}_model.joblib"
    if not src.exists():
        raise FileNotFoundError(f"Model file not found: {src}")

    # Output best_model.joblib
    best_model = cv10_dir / "best_model.joblib"
    shutil.copy(src, best_model)

    # Copy to fold_models/ as well
    fold_models_dir = rf_dir / "fold_models"
    fold_models_dir.mkdir(exist_ok=True)
    shutil.copy(src, fold_models_dir / "best_model.joblib")

    print(f"✔ best_model generated: {best_model}")
    return best_model, cv10_dir, rf_dir


# ============= STEP 4: Call predict.py (Optional) =============
def run_predict(model_dir, in_csv, src_csv, out_csv):
    cmd = [
        "python", "predict.py",
        "--in_csv", in_csv,
        "--source_csv", src_csv,
        "--out_csv", out_csv,
        "--model_dir", str(model_dir),
    ]
    run_cmd(cmd)

# ============= STEP 5: Call Classification Plotting Pipeline (Optional) =============
def run_draw_pipeline(task_dir: Path, skip_existing: bool = True):
    """
    Call Classification_Model/draw_pipline.py (or compatible draw_pipeline.py).
    Output directory is controlled by draw_pipline.py (saved under rf_cls_cv10_t9/).
    """
    cls_root = Path(__file__).resolve().parent  # .../Classification_Model

    # ✅ Compatibility: Prefer existing draw_pipline.py
    candidates = [
        cls_root / "draw_pipline.py",   # Currently existing file
        cls_root / "draw_pipeline.py",  # Future corrected spelling
    ]
    draw_script = next((p for p in candidates if p.is_file()), None)

    if draw_script is None:
        print(f"[WARN] draw_pipline.py / draw_pipeline.py not found. Skipping plotting.")
        print(f"[DEBUG] Contents of Classification_Model directory:")
        for p in sorted(cls_root.iterdir()):
            print(f"   - {p.name}")
        return

    cmd = [
        sys.executable, str(draw_script),
        "--task_dir", str(task_dir.resolve()),
    ]
    if skip_existing:
        cmd += ["--skip_existing"]

    print("=== STEP: Plotting Best Fold Charts (Confusion Matrix + ROC) ===")
    try:
        run_cmd(cmd)
    except Exception as e:
        print("[WARN] Classification plotting failed (Main flow unaffected)")
        print(f"       {e}")

# ============= File Existence Checks =============
def check_morgan_file_exists(morgan_csv_path: Path) -> bool:
    """Check if Morgan feature file exists"""
    if morgan_csv_path.exists():
        print(f"[INFO] Morgan feature file exists, skipping Morgan step: {morgan_csv_path}")
        return True
    return False


def check_model_files_exist(task_dir: Path, threshold: float) -> bool:
    """Check if model related files exist"""
    threshold_int = int(threshold)
    model_dir_name = f"rf_cls_cv10_t{threshold_int}"
    model_dir = task_dir / model_dir_name
    
    if not model_dir.exists():
        # Try finding any directory starting with rf_cls_cv10
        dirs = [d for d in task_dir.iterdir() if d.is_dir() and d.name.startswith("rf_cls_cv10")]
        if not dirs:
            return False
        model_dir = dirs[0]
    
    # Check critical files
    required_files = [
        model_dir / "cv10_metrics.csv",
        model_dir / "cv10" / "best_model.joblib"
    ]
    
    all_exist = all(f.exists() for f in required_files)
    
    if all_exist:
        print(f"[INFO] Model files exist, skipping training step:")
        for f in required_files:
            print(f"  ✓ {f}")
        return True
    
    return False

def check_draw_files_exist(task_dir: Path, rf_dir: Path) -> bool:
    """
    Check if plot files exist.
    Checks for:
    1. .../draw/rf/fold_XX/ROC/roc_train_vs_test.png
    2. .../draw/rf/fold_XX/CM/confmat_test.png
    
    Note: confmat_test.png is actually output as confmat_valid.png in draw_Matrix.py,
    but we check for both as requested.
    """
    # Get best fold
    metrics_file = rf_dir / "cv10_metrics.csv"
    if not metrics_file.exists():
        return False
    
    try:
        df = pd.read_csv(metrics_file)
        if "Acc_class_1" not in df.columns or "fold" not in df.columns:
            return False
        
        # Find fold with max Acc_class_1
        best_row = df.sort_values("Acc_class_1", ascending=False).iloc[0]
        best_fold = int(best_row["fold"])
        print(f"[INFO] Best Fold is fold_{best_fold:02d}")
        
        # Check plot files
        base_draw_dir = task_dir / "draw" / "rf" / f"fold_{best_fold:02d}"
        
        # Check ROC file
        roc_file = base_draw_dir / "ROC" / "roc_train_vs_test.png"
        
        # Check CM file - Note: Checking both possible names
        cm_file_test = base_draw_dir / "CM" / "confmat_test.png"
        cm_file_valid = base_draw_dir / "CM" / "confmat_valid.png"
        
        # If both files exist, skip plotting
        if roc_file.exists() and (cm_file_test.exists() or cm_file_valid.exists()):
            print(f"[INFO] Plot files exist:")
            print(f"  ✓ {roc_file}")
            if cm_file_test.exists():
                print(f"  ✓ {cm_file_test}")
            if cm_file_valid.exists():
                print(f"  ✓ {cm_file_valid}")
            return True
        else:
            print(f"[INFO] Missing plot files:")
            if not roc_file.exists():
                print(f"  ✗ {roc_file} not found")
            if not cm_file_test.exists() and not cm_file_valid.exists():
                print(f"  ✗ Confusion Matrix file not found (confmat_test.png or confmat_valid.png)")
            return False
            
    except Exception as e:
        print(f"[WARN] Error checking plot files: {e}")
        return False


# ============= Main Entry Point =============
def main():
    ap = argparse.ArgumentParser()

    ap.add_argument("--task_name", required=True)
    ap.add_argument("--raw_csv", required=True)
    ap.add_argument("--src_col", required=True)
    ap.add_argument("--threshold", type=float, required=True)
    ap.add_argument("--class_col", default="y_class")

    ap.add_argument("--polymer_cols", nargs="*", default=["SMILE A", "SMILE B", "SMILE C"])
    ap.add_argument("--other_cols", nargs="*", default=[])

    # Prediction related arguments
    ap.add_argument("--do_predict", action="store_true")
    ap.add_argument("--predict_in_csv", default=None)
    ap.add_argument("--predict_source_csv", default=None)
    ap.add_argument("--predict_out_csv", default=None)
    
    # Optional: Force re-run all steps
    ap.add_argument("--force_rerun", action="store_true", 
                   help="Force re-run all steps even if files exist")

    ap.add_argument(
        "--no_draw",
        action="store_true",
        help="Do not plot charts (Default plots Best Fold Confusion Matrix + ROC)",
    )


    args = ap.parse_args()

    # Result Root Directory: e.g., results/SwellingRatio
    task_dir = Path("results") / args.task_name
    task_dir.mkdir(parents=True, exist_ok=True)

    # Features Directory: e.g., results/SwellingRatio/features
    features_dir = task_dir / "features"
    features_dir.mkdir(parents=True, exist_ok=True)

    # Morgan Output Path: Saved in features directory
    raw = Path(args.raw_csv)
    morgan_csv_path = features_dir / f"{raw.stem}_morgan.csv"
    
    # Check if Morgan step should be skipped
    skip_morgan = check_morgan_file_exists(morgan_csv_path) and not args.force_rerun
    morgan_csv = str(morgan_csv_path)

    if not skip_morgan:
        print("=== STEP 1: Morgan Fingerprints (1024) ===")
        run_morgan(args.raw_csv, morgan_csv, args.polymer_cols, args.other_cols)
    else:
        print("=== STEP 1: Morgan Fingerprints (1024) - Skipped (File Exists) ===")
    
    # Check if model training step should be skipped
    skip_training = check_model_files_exist(task_dir, args.threshold) and not args.force_rerun
    
    if not skip_training:
        print("=== STEP 2: Model Training via pipeline.py (10-Fold) ===")
        run_pipeline(morgan_csv, args.src_col, args.threshold, args.class_col, task_dir)
    else:
        print("=== STEP 2: Model Training via pipeline.py (10-Fold) - Skipped (Model Files Exist) ===")
    
    print("=== STEP 3: Auto-select Best Fold with Maximum Acc_class_1 ===")
    best_model, model_dir, rf_dir = select_best_model(task_dir, args.threshold)

    # ========== Auto Prediction ==========
    if args.do_predict:
        print("=== STEP 4: Prediction using best_model ===")

        if args.predict_out_csv:
            out_csv = args.predict_out_csv
        else:
            # Default output path: auto-save to results/<task_name>/
            out_csv = str(task_dir / f"{args.task_name}_predict.csv")

        if not args.predict_in_csv or not args.predict_source_csv:
            raise ValueError("--do_predict requires predict_in_csv and predict_source_csv")

        run_predict(model_dir, args.predict_in_csv, args.predict_source_csv, out_csv)
        print(f"✔ Prediction results saved: {out_csv}")

    # ========== Auto Plotting (Best Fold) Default ON ==========
    if not args.no_draw:
        # Check if plot files exist
        if check_draw_files_exist(task_dir, rf_dir) and not args.force_rerun:
            print("[INFO] Plot files exist, skipping plotting step")
        else:
            run_draw_pipeline(
                task_dir=task_dir,
                skip_existing=not args.force_rerun,
            )
    else:
        print("[INFO] Plotting step skipped (--no_draw specified)")

    print("\n===========================")
    print("Classification Pipeline Completed!")
    print(f"Best Model: {best_model}")
    print(f"Model Directory: {model_dir}")
    if skip_morgan:
        print("✓ Morgan step skipped (File Exists)")
    if skip_training:
        print("✓ Training step skipped (Model Files Exist)")
    print("===========================\n")


if __name__ == "__main__":
    main()